### PR TITLE
Fix some basic docs

### PR DESCRIPTION
**Pull request by Gwened**
Docs were not matching the code regarding dynamic import and mutation arguments.
Also, I added a few clarifications that will help newcomers.

### CODE REVIEW

**Comment by eric-burel** [comment]
@SachaG you may want to check this update, I haven't used the syntax much at this point

**Comment by SachaG** [comment]
Thanks! Some of those seem good but we're actually moving away from `selector`, `input` is the correct variable name now.

**Comment by Gwened** [comment]
I see, I'll pull the 1.15 release of Vulcan-Starter and fix it.
Btw it would be great to offer per-release documentation pages on https://docs.vulcanjs.org/ since the API is evolving fast.

**Comment by Gwened** [comment]
> Thanks! Some of those seem good but we're actually moving away from `selector`, `input` is the correct variable name now.

After upgrading to 1.15 and experimenting, it seems that:

- updateXXX from withUpdate HoC accepts {selector: {_id: ...}, data: ...}
- updateXXX from withUpdate2 HoC accepts {input: {_id: ..., data: ...}}

I reverted my change in mutations.md and was thinking of modifying withUpdate to withUpdate2, but I see that other CRUD mutations also have two versions, so I won't add any more entropy and let you update the documentation as you wish. I suppose removing inconsistencies in the documentation that make Vulcan-newbie life hard and painful is kind of high priority :)

**Pull request merged**
