### PR TITLE
Update features.md

### PR DESCRIPTION
**Pull request by amandeepmittal**
The point of using colons did not make it clear. I think separating them in two sentences will bring more clarity.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks :)

**Comment by amandeepmittal** [comment]
@SachaG I got to see your latest video on YouTube. I'd love to help as much as I can with the project.

**Comment by SachaG** [comment]
Thanks! Helping improve the docs is definitely a great first step :)

**Comment by amandeepmittal** [comment]
One thing I wan to ask, I am unable to push a branch and then open a Pull Request after cloning the repository. Is there a way I can do this? Or do I have to edit the document from the browser and send a PR per edited document?

**Comment by SachaG** [comment]
I'm not sure, when you say you're unable, what exactly is the problem?

**Comment by amandeepmittal** [comment]
I am sorry if I was not clear. I cloned the repo of Vulcan docs and I am currently trying to push a branch which contain changes as a PR. More details in screenshots:

screen shot 2018-02-03 at 4 58 19 pm
screen shot 2018-02-03 at 4 58 32 pm

I am not able to push or create a Pull Request from my local machine.

**Comment by SachaG** [comment]
Oh, you need to clone the repo to your own fork. See https://help.github.com/articles/about-pull-requests/

**Comment by amandeepmittal** [comment]
Thank you. 👍

**Pull request merged**
